### ISSUE TITLE
Lowest Common Ancestor

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#30]
## Write a program to find the lowest common ancestor in binary tree.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by sgavil** [comment]
Hello, I would like to make my contribution

**Comment by BassCoder2808** [comment]
I would like to contribute on this issue

**Comment by HariniJeyaraman** [comment]
Would love to work on this issue

**Comment by pawki07** [comment]
Hey, I would like to contribute to this issue.

**Comment by passionlord** [comment]
i would love to contribute on this

**Comment by abhishektandon** [comment]
Hello, I recently solved a similar problem on HackerRank and I would like to contribute to it.

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge https://github.com/C0D1NG/Data-Structures/pull/78

**Comment by code-value** [comment]
@G1Joshi 

There are some changes in rules for repositories participating in Hacktober 2020. Read Here: https://hacktoberfest.digitalocean.com/hacktoberfest-update
You need to add specific tags to let your repository count in Hacktober 2020.
This has been done in order to reduce spam.

![image](https://user-images.githubusercontent.com/72187158/94993850-724e0c80-05b1-11eb-85ba-b2f32f8e0f8b.png)
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)

**Comment by vallabhiaf** [comment]
working on this :)
